### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by amanjoshi668** [jakebesworth/calibre-dark-theme#1]
I opened a book, right click -> preferences -> styles -> then pasted the file.

I am not able to observe any change

**Comment by jakebesworth** [comment]
4. In Preferences > Userstyle paste contents of CSS file, click OK
5. In Preferences > Theming click Save

**Comment by jakebesworth** [comment]
Will close, but feel free to re-open, or open another if the above isnt' fixed.
